language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6

install:
  - pip3 install -r requirements.txt
script:
  - py.test --cov=./
after_script:
  - pytest test/
after_success:
  - codecov --token=1081ff9a-5648-4de2-8044-b09eb63f7f95